server:
  port: 8080

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    # TODO alpha -> method 변경 후 순서 커스텀
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs

  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

jwt:
  secret: ${JWT_SECRET}

oauth:
  client_id: ${OAUTH_CLIENT_ID}
  redirect_uri: ${OAUTH_REDIRECT_URI}
  client_secret: ${OAUTH_CLIENT_SECRET}

encryption:
  secret_key: ${ENCRYPTION_SECRET_KEY}
  iv: ${ENCRYPTION_IV}

origin:
  frontend:
    prod: ${FRONTEND_PROD_ORIGIN}
    local: ${FRONTEND_LOCAL_ORIGIN}