spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/YI?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

oauth:
  client_id: ${OAUTH_CLIENT_ID}
  redirect_uri: ${OAUTH_REDIRECT_URI}
  client_secret: ${OAUTH_CLIENT_SECRET}

encryption:
  secret_key: ${ENCRYPTION_SECRET_KEY}
  iv: ${ENCRYPTION_IV}

