spring:
  profiles:
    active:
      local

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    # TODO alpha -> method 변경 후 순서 커스텀
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs

  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**